# Generated by Django 6.0.3 on 2026-05-01 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['member', 'is_paid'], name='fines_fine_member__554e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['fine_type'], name='fines_fine_fine_ty_5fc703_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['is_paid', 'issued_date'], name='fines_fine_is_paid_b07b3c_idx'),
        ),
    ]
