# Generated by Django 6.0.3 on 2026-05-01 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('fulfilled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('is_frozen', models.BooleanField(default=False)),
                ('freeze_until', models.DateField(blank=True, null=True)),
                ('pickup_branch', models.CharField(blank=True, max_length=255)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placed_date'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('renewed_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='catalog.bookinstance')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
