# Generated by Django 6.0.3 on 2026-05-01 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('circulation', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holdreservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_reservations', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='holdreservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_reservations', to='members.memberprofile'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['member', 'return_date'], name='circulation_member__1c4b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['book_instance', 'return_date'], name='circulation_book_in_401a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['due_date'], name='circulation_due_dat_a738c9_idx'),
        ),
        migrations.AddIndex(
            model_name='holdreservation',
            index=models.Index(fields=['book', 'status'], name='circulation_book_id_d5160f_idx'),
        ),
        migrations.AddIndex(
            model_name='holdreservation',
            index=models.Index(fields=['member', 'status'], name='circulation_member__f60395_idx'),
        ),
        migrations.AddIndex(
            model_name='holdreservation',
            index=models.Index(fields=['status'], name='circulation_status_ddab95_idx'),
        ),
    ]
