# Generated by Django 6.0.3 on 2026-05-01 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisitions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesuggestion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['status'], name='acquisition_status_919c25_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['created_at'], name='acquisition_created_de70b1_idx'),
        ),
    ]
