# Generated by Django 6.0.3 on 2026-05-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='catalog_aut_last_na_73102a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dewey_decimal', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.genre')),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('isbn_10', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('isbn_13', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='book_covers/')),
                ('dewey_decimal', models.CharField(blank=True, max_length=20)),
                ('lc_classification', models.CharField(blank=True, max_length=50)),
                ('subject_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('available_copies', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author')),
                ('genres', models.ManyToManyField(related_name='books', to='catalog.genre')),
                ('languages', models.ManyToManyField(related_name='books', to='catalog.language')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.publisher')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('call_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On Loan'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shelf_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='catalog.book')),
            ],
            options={
                'ordering': ['book__title', 'barcode'],
                'indexes': [models.Index(fields=['barcode'], name='catalog_boo_barcode_872dfc_idx'), models.Index(fields=['status'], name='catalog_boo_status_c7d7a0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn_13'], name='catalog_boo_isbn_13_683221_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='catalog_boo_slug_7fab6a_idx'),
        ),
    ]
